name: Run Python Sanity for Lambda

on:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '**/README.md'
      - 'vimeo-uploader-python/**'
      - 'vimeo-uploader-swift/**'
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - '**/README.md'
      - 'vimeo-uploader-python/**'
      - 'vimeo-uploader-swift/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vimeo-uploader-lambda
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install FFMpeg
      run: sudo apt-get install ffmpeg
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 moviepy pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download and install the protobuf compiler
      run: |
        wget --tries=5 --connect-timeout=5 -O protoc-linux-x86_64.zip \
          https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip 
        sudo apt-get install unzip
        unzip protoc-linux-x86_64.zip -d protoc-linux-x86_64
        echo "protoc-linux-x86_64/bin" >> $GITHUB_PATH
    - name: Generate protobuf
      run: |
        mkdir -p core/generated
        protoc --proto_path=proto -I=proto --python_out=core/generated proto/model.proto
    - name: Lint with flake8
      run: |
        flake8 app.py core --exclude=core/generated --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app.py core --exclude=core/generated --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests
      run: python -m pytest
