name: Run Python Sanity for Lambda

on:
  pull_request:
    paths: vimeo-uploader-lambda/**
  push:
    branches: main
    paths: vimeo-uploader-lambda/**

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vimeo-uploader-lambda
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install FFMpeg
      run: sudo apt-get install ffmpeg
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 moviepy pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 src ---exclude=src/generated --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src ---exclude=src/generated --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests
      run: python -m pytest
